import connectDB from "../lib/mongoose";
import Masjid from "../models/Masjid";

export const MASJID_DB_PDF = [

  // ==================== DHOORAJI ====================
  {
    name: "Nakhuda Masjid (Katchi Memon Society)",
    area: "Dhooraji",
    lat: 24.8589589,
    lng: 67.0295335,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Habibia Masjid",
    area: "Dhooraji",
    lat: 24.862,
    lng: 67.032,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Mustafa Masjid",
    area: "Dhooraji",
    lat: 24.863,
    lng: 67.031,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Zaitoon Ashraf (Faran Society)",
    area: "Dhooraji",
    lat: 24.864,
    lng: 67.033,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Bismillah Shah Bukhari",
    area: "Dhooraji",
    lat: 24.865,
    lng: 67.034,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Faizan Mushtaq Masjid",
    area: "Dhooraji",
    lat: 24.866,
    lng: 67.033,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Jamal Mustafa Masjid",
    area: "Dhooraji",
    lat: 24.867,
    lng: 67.034,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Al-Farooq",
    area: "Dhooraji",
    lat: 24.868,
    lng: 67.033,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Ghaffar",
    area: "Dhooraji",
    lat: 24.869,
    lng: 67.034,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Faizan Farooq Azam Masjid - KDA Scheme 1 (Near Peer Pagara House)",
    area: "Dhooraji / KDA Scheme 1",
    lat: 24.871,
    lng: 67.035,
    parking: false,
    timings: { juma: "3:30" },
  },
  {
    name: "Aqsa Masjid (M Ali Society)",
    area: "Dhooraji",
    lat: 24.872,
    lng: 67.036,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Faizan Ishq-e-Rasool Masjid (Depo Wali Gali, M Ali Society)",
    area: "Dhooraji",
    lat: 24.873,
    lng: 67.037,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Siddiqia (Tipu Sultan Road)",
    area: "Dhooraji",
    lat: 24.874,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Umar Farooq Masjid (Saylani Office, Bakery Hill Park)",
    area: "Dhooraji",
    lat: 24.875,
    lng: 67.039,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Saylani (Jaye Namaz) Tipu Sultan Bridge",
    area: "Dhooraji",
    lat: 24.876,
    lng: 67.04,
    parking: false,
    timings: { juma: "1:30" },
  },

  // ==================== JAMSHED ROAD ====================
  {
    name: "Zainab Masjid",
    area: "Jamshed Road",
    lat: 24.881,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Ismail Giga Masjid",
    area: "Jamshed Road",
    lat: 24.882,
    lng: 67.043,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Memon Masjid (Hyderabad Colony)",
    area: "Jamshed Road",
    lat: 24.883,
    lng: 67.044,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Hanfia Masjid (Bank Al-Habib Wali Gali, Pick N Save ke Saamne)",
    area: "Jamshed Road",
    lat: 24.884,
    lng: 67.045,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Arain Masjid",
    area: "Jamshed Road",
    lat: 24.885,
    lng: 67.046,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Anas Fatima Masjid (Hyderabad Colony)",
    area: "Jamshed Road",
    lat: 24.886,
    lng: 67.047,
    parking: false,
    timings: { juma: "1:25" },
  },
  {
    name: "Fatimi Masjid",
    area: "Jamshed Road",
    lat: 24.887,
    lng: 67.048,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faiz Raza Masjid (Total Petrol Pump ke Saamne)",
    area: "Jamshed Road",
    lat: 24.888,
    lng: 67.049,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Faizan Sunnat Masjid (Rani Lawn ke Saamne)",
    area: "Jamshed Road",
    lat: 24.889,
    lng: 67.05,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Abul Qasim Masjid (Meezan Bank Wali Gali)",
    area: "Jamshed Road",
    lat: 24.89,
    lng: 67.051,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Faizan Mustafa Masjid (Jail Road)",
    area: "Jamshed Road",
    lat: 24.891,
    lng: 67.052,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Faizan Ameer Muawiya (Razi Allah Anhu) Masjid (Pick N Save Wali Gali)",
    area: "Jamshed Road",
    lat: 24.892,
    lng: 67.053,
    parking: false,
    timings: { juma: "3:15" },
  },
  {
    name: "Faizan Umme Attar Masjid (Bilal Autos ke Nzdek)",
    area: "Jamshed Road",
    lat: 24.893,
    lng: 67.054,
    parking: false,
    timings: { juma: "2:45" },
  },
  {
    name: "Anwar-e-Madina Masjid (Qudsi Masjid Wali Gali)",
    area: "Jamshed Road",
    lat: 24.894,
    lng: 67.055,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Faizan Ishq-e-Rasool Masjid (Mariam Lawn Wali Gali)",
    area: "Jamshed Road",
    lat: 24.895,
    lng: 67.056,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Siddiq Akbar Masjid (Saylani Office, Peebles Chournaqi ke Paas)",
    area: "Jamshed Road",
    lat: 24.896,
    lng: 67.057,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Qasim Masjid (The Court Residency ke Nzdek, Muslim Abad)",
    area: "Jamshed Road",
    lat: 24.897,
    lng: 67.058,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Moti Masjid (Clayton Quarters)",
    area: "Jamshed Road",
    lat: 24.898,
    lng: 67.059,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Baghdadi Masjid (Martin Quarters)",
    area: "Jamshed Road",
    lat: 24.899,
    lng: 67.06,
    parking: false,
    timings: { juma: "3:45" },
  },
  {
    name: "CMC Jaye Namaz",
    area: "Jamshed Road",
    lat: 24.9,
    lng: 67.061,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Madrasa Noor Syed Zain ul Abideen (Razi Allah Anhu) Jaye Namaz (Near Pioneer Pan Shop)",
    area: "Jamshed Road",
    lat: 24.901,
    lng: 67.062,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Sahaba wa Ahle Bait Jaye Namaz (Descent Bouse Cosmopolitan Society)",
    area: "Jamshed Road",
    lat: 24.902,
    lng: 67.063,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Markaz Mustafa (Muslim Abad No. 15) Jaye Namaz",
    area: "Jamshed Road",
    lat: 24.903,
    lng: 67.064,
    parking: false,
    timings: { juma: "2:00" },
  },

  // ==================== PIB COLONY ====================
  {
    name: "Aalmi Madni Markaz Faizan-e-Madina",
    area: "PIB Colony",
    lat: 24.9066294,
    lng: 67.0826949,
    parking: false,
    timings: { juma: "3:30" },
  },
  {
    name: "Hanfia Masjid",
    area: "PIB Colony",
    lat: 24.907,
    lng: 67.082,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Ghous Azam Masjid",
    area: "PIB Colony",
    lat: 24.908,
    lng: 67.083,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Attar Masjid",
    area: "PIB Colony",
    lat: 24.909,
    lng: 67.084,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Kehtri Masjid",
    area: "PIB Colony",
    lat: 24.91,
    lng: 67.085,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Madni Masjid",
    area: "PIB Colony",
    lat: 24.911,
    lng: 67.083,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Milad Masjid",
    area: "PIB Colony",
    lat: 24.912,
    lng: 67.084,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Qadri Masjid",
    area: "PIB Colony",
    lat: 24.913,
    lng: 67.085,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Ahmad Raza Masjid",
    area: "PIB Colony",
    lat: 24.914,
    lng: 67.086,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Makrani Masjid",
    area: "PIB Colony",
    lat: 24.915,
    lng: 67.087,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Faizan Auliya Masjid",
    area: "PIB Colony",
    lat: 24.916,
    lng: 67.085,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Faizan Aisha Siddiqua Masjid (Haji Anil Gotha Sindhi Paja)",
    area: "PIB Colony",
    lat: 24.917,
    lng: 67.086,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Fatima Masjid (Plot No. 14)",
    area: "PIB Colony",
    lat: 24.918,
    lng: 67.087,
    parking: false,
    timings: { juma: "2:05" },
  },
  {
    name: "Faizan Umme Kulthoom Masjid (Usmani Colony Jahangir Road, Yadgar Fish ke Peeche)",
    area: "PIB Colony",
    lat: 24.919,
    lng: 67.088,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Ghousia (Katiana Complex Wali Gali)",
    area: "PIB Colony",
    lat: 24.92,
    lng: 67.089,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Bilal (Sabila Ejaz Colony)",
    area: "PIB Colony",
    lat: 24.921,
    lng: 67.09,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Halima Sadia Masjid (Filmistan)",
    area: "PIB Colony",
    lat: 24.922,
    lng: 67.091,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Ghous Azam Masjid (Waqas Gas Wali Gali, Martin Quarters)",
    area: "PIB Colony",
    lat: 24.923,
    lng: 67.092,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Jamia Masjid Auliya (Nafees Abad)",
    area: "PIB Colony",
    lat: 24.924,
    lng: 67.093,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faran (Martin Road)",
    area: "PIB Colony",
    lat: 24.925,
    lng: 67.094,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Hoor (Central Jail)",
    area: "PIB Colony",
    lat: 24.926,
    lng: 67.095,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Nizam ud Din (Zam Zam Medical Wali Gali)",
    area: "PIB Colony",
    lat: 24.927,
    lng: 67.096,
    parking: false,
    timings: { juma: "2:30" },
  },

  // ==================== HUSSAINABAD ====================
  {
    name: "Jamia Masjid Wali Muhammad (DY Comfort Yaseen Abad)",
    area: "Hussainabad",
    lat: 24.93,
    lng: 67.065,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Yaseen Abad (Gulshan Shamim)",
    area: "Hussainabad",
    lat: 24.931,
    lng: 67.066,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Jamia Masjid Faizan Sunnat (Block 14 Dastgir)",
    area: "Hussainabad",
    lat: 24.932,
    lng: 67.067,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Memon Masjid (Bantwa Nagar)",
    area: "Hussainabad",
    lat: 24.933,
    lng: 67.068,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Jamia Masjid Qadria Bhungoriya Goth Block 2",
    area: "Hussainabad",
    lat: 24.934,
    lng: 67.069,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Muhammadi (Azam Nagar)",
    area: "Hussainabad",
    lat: 24.935,
    lng: 67.07,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Mustafa (Azam Nagar)",
    area: "Hussainabad",
    lat: 24.936,
    lng: 67.071,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Noor (Block 19 Federal B Area)",
    area: "Hussainabad",
    lat: 24.937,
    lng: 67.072,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Muhammadi (DT Block 12 Gulberg)",
    area: "Hussainabad",
    lat: 24.938,
    lng: 67.073,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Ameer Muawiya Masjid (Bhungoriya Gotha)",
    area: "Hussainabad",
    lat: 24.939,
    lng: 67.074,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Faizan Aisha Siddiqua (Aisha Nagar)",
    area: "Hussainabad",
    lat: 24.94,
    lng: 67.075,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Sahaba Masjid (Karachi Complex Nzdek Baloch Hotel)",
    area: "Hussainabad",
    lat: 24.941,
    lng: 67.076,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Madina Masjid (Rajputana Colony)",
    area: "Hussainabad",
    lat: 24.942,
    lng: 67.077,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Hadaiq Bakhsh Shareef Abad",
    area: "Hussainabad",
    lat: 24.943,
    lng: 67.078,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Attar Masjid (Khalifa Hotel Ikram Abad)",
    area: "Hussainabad",
    lat: 24.944,
    lng: 67.079,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Jamia Masjid Faizan Ghous Azam (Nzdek Dastgir School)",
    area: "Hussainabad",
    lat: 24.945,
    lng: 67.08,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Al-Mustafa Masjid (Plot R 680 Federal B Area)",
    area: "Hussainabad",
    lat: 24.946,
    lng: 67.081,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Aqsa Block 15",
    area: "Hussainabad",
    lat: 24.947,
    lng: 67.082,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Noorani (Block 20)",
    area: "Hussainabad",
    lat: 24.948,
    lng: 67.083,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Allah Wali Masjid No. 5 Moosa Colony",
    area: "Hussainabad",
    lat: 24.949,
    lng: 67.084,
    parking: false,
    timings: { juma: "2:40" },
  },
  {
    name: "Jamia Masjid Arfania",
    area: "Hussainabad",
    lat: 24.95,
    lng: 67.085,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Quba (Muhammadi Colony Main Market)",
    area: "Hussainabad",
    lat: 24.951,
    lng: 67.086,
    parking: false,
    timings: { juma: "3:15" },
  },
  // Hussainabad page 2
  {
    name: "Jamia Memon Masjid (Siddiq Abad)",
    area: "Hussainabad",
    lat: 24.952,
    lng: 67.087,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Noori Masjid Ali Abad (Tabba Heart Hospital ke Muqabil)",
    area: "Hussainabad",
    lat: 24.953,
    lng: 67.088,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Madina Masjid (Kareem Abad)",
    area: "Hussainabad",
    lat: 24.954,
    lng: 67.089,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Zainab Masjid (Hussain Abad)",
    area: "Hussainabad",
    lat: 24.955,
    lng: 67.09,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Saffa (Aziz Abad Block 2)",
    area: "Hussainabad",
    lat: 24.956,
    lng: 67.091,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Ismail Saylani Masjid (Bantwa Town)",
    area: "Hussainabad",
    lat: 24.957,
    lng: 67.092,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Attar Masjid (United Bakery ke Nzdek, Kareem Abad)",
    area: "Hussainabad",
    lat: 24.958,
    lng: 67.093,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Almas (Aziz Abad Block 8)",
    area: "Hussainabad",
    lat: 24.959,
    lng: 67.094,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Madina Masjid (Aziz Abad)",
    area: "Hussainabad",
    lat: 24.96,
    lng: 67.095,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Khadija-tul-Kubra Masjid (Aziz Abad)",
    area: "Hussainabad",
    lat: 24.961,
    lng: 67.096,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Nujaymi (Nujaymi Bazar) Kareem Abad",
    area: "Hussainabad",
    lat: 24.962,
    lng: 67.097,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Jamia Masjid Farooq (Aziz Abad Block 8)",
    area: "Hussainabad",
    lat: 24.963,
    lng: 67.098,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Darbar Sultani Masjid",
    area: "Hussainabad",
    lat: 24.964,
    lng: 67.099,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Gulshan Masjid (Block 4)",
    area: "Hussainabad",
    lat: 24.965,
    lng: 67.1,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Ibrahim Masjid (Block 6)",
    area: "Hussainabad",
    lat: 24.966,
    lng: 67.101,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Ghousia (Block 11)",
    area: "Hussainabad",
    lat: 24.967,
    lng: 67.102,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Ghousia (Block 17)",
    area: "Hussainabad",
    lat: 24.968,
    lng: 67.103,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Noorani (Block 12)",
    area: "Hussainabad",
    lat: 24.969,
    lng: 67.104,
    parking: false,
    timings: { juma: "3:40" },
  },
  {
    name: "Markazi Jamia Masjid Faizan Auliya Federal B Area Block 7",
    area: "Hussainabad",
    lat: 24.97,
    lng: 67.105,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Farooq Azam (Block 13)",
    area: "Hussainabad",
    lat: 24.971,
    lng: 67.106,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Jamia Masjid Umme Attar (Aziz Abad Industrial Area)",
    area: "Hussainabad",
    lat: 24.972,
    lng: 67.107,
    parking: false,
    timings: { juma: "1:15" },
  },

  // ==================== NORTH NAZIMABAD ====================
  {
    name: "Alimia Masjid Block A",
    area: "North Nazimabad",
    lat: 24.9245746,
    lng: 67.0351028,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Masjid Faizan Attar Khalifa Abad Block S",
    area: "North Nazimabad",
    lat: 24.925,
    lng: 67.036,
    parking: false,
    timings: { juma: "2:10" },
  },
  {
    name: "Masjid Faizan Ramzan Al-Fazal Plaza Block B",
    area: "North Nazimabad",
    lat: 24.926,
    lng: 67.037,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Mohri Masjid Khundu Gotha Block B",
    area: "North Nazimabad",
    lat: 24.927,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:25" },
  },
  {
    name: "Masjid Faizan Ameer Hamza Block H",
    area: "North Nazimabad",
    lat: 24.928,
    lng: 67.039,
    parking: false,
    timings: { juma: "2:10" },
  },
  {
    name: "Masjid Faizan Sahaba Bantu Ameen Complex Block M",
    area: "North Nazimabad",
    lat: 24.929,
    lng: 67.04,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Masjid Faizan Anbiya Block L",
    area: "North Nazimabad",
    lat: 24.93,
    lng: 67.041,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Masjid Faizan Uwais Qarni Peoples Colony",
    area: "North Nazimabad",
    lat: 24.931,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Masjid Faizan Auliya Arfat Town",
    area: "North Nazimabad",
    lat: 24.932,
    lng: 67.043,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Noor Mohri Nusrat Bhutto Colony",
    area: "North Nazimabad",
    lat: 24.933,
    lng: 67.044,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Bhzad Lucknowi Sunni Hussain Chournaqi",
    area: "North Nazimabad / Chournaqi",
    lat: 24.934,
    lng: 67.045,
    parking: false,
    timings: { juma: "3:30" },
  },
  {
    name: "Jamia Masjid Ghousia Lundi Kotel Chournaqi",
    area: "North Nazimabad",
    lat: 24.935,
    lng: 67.046,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Al-Markaz Islami Block B",
    area: "North Nazimabad",
    lat: 24.936,
    lng: 67.047,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Masjid Darul Masajid Marhaba Gallaksi Block M",
    area: "North Nazimabad",
    lat: 24.937,
    lng: 67.048,
    parking: false,
    timings: { juma: "" },
  },

  // ==================== NAZIMABAD ====================
  {
    name: "Jamia Masjid Faizan Mecca (Al-Hassan Chowk) Block 1",
    area: "Nazimabad",
    lat: 24.9066312,
    lng: 67.0333352,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Ameer Muawiya Razi Allah Anhu Block 1",
    area: "Nazimabad",
    lat: 24.907,
    lng: 67.034,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Masjid Faizan Fatima Al-Zahra Razi Allah Anha Block 1",
    area: "Nazimabad",
    lat: 24.908,
    lng: 67.035,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Nizamia (Muttasil Orange Abad Jalal Abad Colony) Block 1",
    area: "Nazimabad",
    lat: 24.909,
    lng: 67.036,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Quba (Siraj Colony) Block 1",
    area: "Nazimabad",
    lat: 24.91,
    lng: 67.037,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Bilal (Jalal Abad Colony) Block 1",
    area: "Nazimabad",
    lat: 24.911,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Anbri (Jahangir Abad) Block 1",
    area: "Nazimabad",
    lat: 24.912,
    lng: 67.039,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Waqar ul Madina (Subhan Bakery Wali Gali) Block 1",
    area: "Nazimabad",
    lat: 24.913,
    lng: 67.04,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Jamia Masjid Ameer Hamza Razi Allah Anhu Block 2",
    area: "Nazimabad",
    lat: 24.9177745,
    lng: 67.0278796,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Mustafa Masjid Block 2",
    area: "Nazimabad",
    lat: 24.914,
    lng: 67.041,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Zam Zam Block 2",
    area: "Nazimabad",
    lat: 24.915,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Faizan Jamal Mustafa Block 2",
    area: "Nazimabad",
    lat: 24.916,
    lng: 67.043,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Allah Wali Block 2",
    area: "Nazimabad",
    lat: 24.917,
    lng: 67.044,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Shabi Jamia Masjid Block 2",
    area: "Nazimabad",
    lat: 24.918,
    lng: 67.045,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Tayyiba Block 2",
    area: "Nazimabad",
    lat: 24.919,
    lng: 67.046,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Usmania (Nzdek Mulungi Hotel) Block 2",
    area: "Nazimabad",
    lat: 24.92,
    lng: 67.047,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Hassan Block 3",
    area: "Nazimabad",
    lat: 24.921,
    lng: 67.048,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Faizan Siddiq Akbar Razi Allah Anhu Block 3",
    area: "Nazimabad",
    lat: 24.922,
    lng: 67.049,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Jamia Masjid Noor ul Islam Block 3",
    area: "Nazimabad",
    lat: 24.9177745,
    lng: 67.0278796,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Shaeer Arkaid (Jaye Namaz) Block 3",
    area: "Nazimabad",
    lat: 24.923,
    lng: 67.05,
    parking: false,
    timings: { juma: "" },
  },
  {
    name: "Faizan Hamedia Masjid Block 3",
    area: "Nazimabad",
    lat: 24.924,
    lng: 67.051,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Ghousia (Bada Maidaan) Block 3",
    area: "Nazimabad",
    lat: 24.925,
    lng: 67.052,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Jamia Masjid Aqsa (Chota Maidaan) Block 3",
    area: "Nazimabad",
    lat: 24.926,
    lng: 67.053,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Faizan Ali Razi Allah Anhu Block 4",
    area: "Nazimabad",
    lat: 24.927,
    lng: 67.054,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Jamia Masjid Auliya Block 4",
    area: "Nazimabad",
    lat: 24.928,
    lng: 67.055,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Faizan Attar Block 4",
    area: "Nazimabad",
    lat: 24.929,
    lng: 67.056,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Jami ul Madina (Jaye Namaz) Block 4",
    area: "Nazimabad",
    lat: 24.93,
    lng: 67.057,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Noor Bilal (Majahed Colony) Block 4",
    area: "Nazimabad",
    lat: 24.931,
    lng: 67.058,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Ahbab (Nzdek Abbasi Hospital) Block 5",
    area: "Nazimabad",
    lat: 24.932,
    lng: 67.059,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamaah Masjid Aalamgir (Nzdek Railwey Bank Bada Maidaan) Block 5",
    area: "Nazimabad",
    lat: 24.933,
    lng: 67.06,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Khairulbashri (Papos Nagar Qabarstan) Block 5",
    area: "Nazimabad",
    lat: 24.934,
    lng: 67.061,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Gulzar Saeediya Block 5",
    area: "Nazimabad",
    lat: 24.935,
    lng: 67.062,
    parking: false,
    timings: { juma: "2:10" },
  },
  {
    name: "Jamia Masjid Umar Block 5",
    area: "Nazimabad",
    lat: 24.936,
    lng: 67.063,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Raza (Khilaft Chowk Paposh Nagar) Block 5",
    area: "Nazimabad",
    lat: 24.937,
    lng: 67.064,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Darul Islam Masjid (Orangi Abad) Block 5",
    area: "Nazimabad",
    lat: 24.938,
    lng: 67.065,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Hanfia Masjid (Bada Maidaan Orangi Abad) Block 5",
    area: "Nazimabad",
    lat: 24.939,
    lng: 67.066,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Faizan Usman Ghani (Saylani Welfare Trust) Block 5",
    area: "Nazimabad",
    lat: 24.94,
    lng: 67.067,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Noor (5C)",
    area: "Nazimabad",
    lat: 24.941,
    lng: 67.068,
    parking: false,
    timings: { juma: "2:25" },
  },

  // ==================== GULISTAN JOHAR ====================
  {
    name: "Jamia Masjid Anwar Mustafa (Dhani Bakhsh Gotha)",
    area: "Gulistan Johar",
    lat: 24.9065077,
    lng: 67.1254218,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Usman Ghani (Razi Allah Anhu) Block 15",
    area: "Gulistan Johar",
    lat: 24.907,
    lng: 67.126,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Attar Barkatim ul Aalim (Mausimiyat A24/25 Rehman Vlaz Okhayi Market)",
    area: "Gulistan Johar",
    lat: 24.908,
    lng: 67.127,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Jamia Masjid Diyar Mustafa (Dhani Bakhsh Gotha)",
    area: "Gulistan Johar",
    lat: 24.909,
    lng: 67.128,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Masjid Faizan Zam Zam (Falak Naz Corner)",
    area: "Gulistan Johar",
    lat: 24.91,
    lng: 67.129,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Fatima Zahra (Nzdek Semama Shopping Mall Farhan Trim Line Gulistan Johar Block 16)",
    area: "Gulistan Johar",
    lat: 24.911,
    lng: 67.13,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Siddiq Akbar Razi Allah Anhu (Roofi Peeradzanz Block 18)",
    area: "Gulistan Johar",
    lat: 24.912,
    lng: 67.131,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Muhammadi Masjid (Nzdek Asma Medical Block 4)",
    area: "Gulistan Johar",
    lat: 24.913,
    lng: 67.132,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Faiz Madina Masjid (Block 5 Nzdek Jadeed Super Store)",
    area: "Gulistan Johar",
    lat: 24.914,
    lng: 67.133,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Masjid Diyar Habeeb Johar Complex",
    area: "Gulistan Johar",
    lat: 24.915,
    lng: 67.134,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Raqeeba Ibrahim Masjid Salli Tower",
    area: "Gulistan Johar",
    lat: 24.916,
    lng: 67.135,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Muhammadi Gulshan Complex Phase 1 Gulistan Johar",
    area: "Gulistan Johar",
    lat: 24.917,
    lng: 67.136,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Al-Kareem Zooraman Residentcy Mausimiyat",
    area: "Gulistan Johar",
    lat: 24.918,
    lng: 67.137,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Faizan Mustafa (Nzdek Semama Shopping Mall)",
    area: "Gulistan Johar",
    lat: 24.919,
    lng: 67.138,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Bilal Masjid (Safora Gotha Momen Qabarstan)",
    area: "Gulistan Johar",
    lat: 24.92,
    lng: 67.139,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Numra (Nzdek Shabeen Public School Block 2)",
    area: "Gulistan Johar",
    lat: 24.921,
    lng: 67.14,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Nematia (Nzdek Sadkin Grammer School Block 2)",
    area: "Gulistan Johar",
    lat: 24.922,
    lng: 67.141,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Anwar Attar Block 3 Gulistan Johar",
    area: "Gulistan Johar",
    lat: 24.923,
    lng: 67.142,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Hazrat Mubarak Rehmatullah Alaihi Jahangir Town",
    area: "Gulistan Johar",
    lat: 24.924,
    lng: 67.143,
    parking: false,
    timings: { juma: "2:10" },
  },
  {
    name: "Markazi Jamia Masjid Zainab Roomi Gulshan Aisha Maliir Link Road Block 9",
    area: "Gulistan Johar",
    lat: 24.925,
    lng: 67.144,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Jamia Masjid Faizan Ahmad Raza Block 9 Maliir Link Road Kashif Pharmacy",
    area: "Gulistan Johar",
    lat: 24.926,
    lng: 67.145,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Bashmi Younik Masjid Classic Apartment Block 15",
    area: "Gulistan Johar",
    lat: 24.927,
    lng: 67.146,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Bashmi Masjid Block 3 Gulistan Johar Bl Road Nzdek Javed Bl Wio Karachi",
    area: "Gulistan Johar",
    lat: 24.928,
    lng: 67.147,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Jamia Masjid Faizan Khulafa Rashideen Dhani Bakhsh Gotha Gulistan Johar Block 9",
    area: "Gulistan Johar",
    lat: 24.929,
    lng: 67.148,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jamia Masjid Faizan Bilal Bakhtawar Gotha Gulistan Johar Block 9",
    area: "Gulistan Johar",
    lat: 24.93,
    lng: 67.149,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Faisalannoor Muhammadia Engineering Society Gulistan Johar Block 08",
    area: "Gulistan Johar",
    lat: 24.931,
    lng: 67.15,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Shakeel Garden Mausimiyat",
    area: "Gulistan Johar",
    lat: 24.932,
    lng: 67.151,
    parking: false,
    timings: { juma: "1:45" },
  },

  // ==================== DHA ====================
  {
    name: "Memon Masjid Saylani House (Phase-2 Ext., DHA)",
    area: "DHA Phase 2",
    lat: 24.8433203,
    lng: 67.0541652,
    parking: true,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan-e-Ali (Phase 2, DHA)",
    area: "DHA Phase 2",
    lat: 24.844,
    lng: 67.055,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan-e-Ramzan (9th-10th Comm. Street, Phase-4, DHA)",
    area: "DHA Phase 4",
    lat: 24.8277091,
    lng: 67.0598831,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan-e-Ismail (Ayubi Com.St 2, near DHA Suffa University)",
    area: "DHA Phase 4",
    lat: 24.828,
    lng: 67.061,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Faizan-e-Islam (Kh-e-Seher, Phase-7, DHA)",
    area: "DHA Phase 7",
    lat: 24.8199298,
    lng: 67.074944,
    parking: true,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan-e-Ghaus Pak (Kh-e-Hafiz, Phase-6, DHA)",
    area: "DHA Phase 6",
    lat: 24.795,
    lng: 67.0605556,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan-e-Ishqe Rasool (Phase 6, DHA)",
    area: "DHA Phase 6",
    lat: 24.796,
    lng: 67.061,
    parking: true,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan-e-Farooq e Azam (Chota Bukhari Comm. Lane 5, Phase 6, DHA)",
    area: "DHA Phase 6",
    lat: 24.797,
    lng: 67.062,
    parking: true,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan-e-Quran (Bukhari Comm. Area, Phase 6, DHA)",
    area: "DHA Phase 6",
    lat: 24.798,
    lng: 67.063,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Madrassa Qadria Barkatia (Nishat Com. Area, Phase 6 DHA)",
    area: "DHA Phase 6",
    lat: 24.799,
    lng: 67.064,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Ameer Hamza (Nishat Commercial, Phase 6 DHA)",
    area: "DHA Phase 6",
    lat: 24.8,
    lng: 67.065,
    parking: true,
    timings: { juma: "1:20" },
  },
  {
    name: "Masjid-e-Auliah Misri Shah (Kh-e-Bukhari, Phase 6 DHA)",
    area: "DHA Phase 6",
    lat: 24.801,
    lng: 67.066,
    parking: true,
    timings: { juma: "2:45" },
  },
  {
    name: "Faizan-e-Maryam (Badar Commercial, Phase 5 DHA)",
    area: "DHA Phase 5",
    lat: 24.8108333,
    lng: 67.0580556,
    parking: true,
    timings: { juma: "1:25" },
  },
  {
    name: "Faizan-e-Muhammad Ali (Badr Com.Area, behind Marvi Store)",
    area: "DHA Phase 5",
    lat: 24.811,
    lng: 67.059,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Mubarak Masjid Seaview (Kh-e-Bahria, Phase-5 Ext., DHA)",
    area: "DHA Phase 5",
    lat: 24.812,
    lng: 67.06,
    parking: true,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan-e-Abubaker (Tauheed Commercial Area, Phase 5, DHA)",
    area: "DHA Phase 5",
    lat: 24.813,
    lng: 67.061,
    parking: true,
    timings: { juma: "1:20" },
  },
  {
    name: "Bilal Masjid (Tauheed Commercial Area, Phase 5, DHA)",
    area: "DHA Phase 5",
    lat: 24.814,
    lng: 67.062,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Sakina Sultan Masjid (Kh-e-Shaheen, Phase-8, DHA)",
    area: "DHA Phase 8",
    lat: 24.7692678,
    lng: 67.0768936,
    parking: true,
    timings: { juma: "1:25" },
  },
  {
    name: "Essa Masjid (Kh-e-Shujaat, Phase-8, DHA)",
    area: "DHA Phase 8",
    lat: 24.77,
    lng: 67.078,
    parking: true,
    timings: { juma: "1:15" },
  },
  {
    name: "Amina Wali Masjid (Kh-e-Bilal, Phase-8, DHA)",
    area: "DHA Phase 8",
    lat: 24.771,
    lng: 67.079,
    parking: true,
    timings: { juma: "1:35" },
  },
  {
    name: "Ahmed Masjid (Sahil Street Sector E8, Phase-8, DHA)",
    area: "DHA Phase 8",
    lat: 24.772,
    lng: 67.08,
    parking: true,
    timings: { juma: "1:30" },
  },
  {
    name: "Arafat Masjid (Kh-e-Arafat, 36th Street, Phase-8, DHA)",
    area: "DHA Phase 8",
    lat: 24.773,
    lng: 67.081,
    parking: false,
    timings: { juma: "1:15" },
  },

  // ==================== CLIFTON / CIVIL LINES / GIZRI ====================
  {
    name: "Faizan-e-Bismillah (Civil Lines, Clifton)",
    area: "Clifton",
    lat: 24.8262498,
    lng: 67.0335967,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan-e-Baghdad (Bath Island, Clifton)",
    area: "Clifton",
    lat: 24.823,
    lng: 67.028,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Noor Masjid (Bath Island, Clifton)",
    area: "Clifton",
    lat: 24.824,
    lng: 67.029,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Sabri Masjid (Street 7, Bath Island, Clifton)",
    area: "Clifton",
    lat: 24.825,
    lng: 67.03,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Hilal-e-Ahmer Masjid (Hilal-e-Ahmer Hospital, Near 3 Talwar)",
    area: "Clifton",
    lat: 24.8285508,
    lng: 67.03704,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Qadria Masjid (Lilly Bridge, Civil Lines)",
    area: "Clifton",
    lat: 24.826,
    lng: 67.031,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan-e-Mustafa (Zero Line, Dehli Colony)",
    area: "Clifton",
    lat: 24.827,
    lng: 67.032,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Islamia Masjid (Race Course, Frere Town)",
    area: "Clifton",
    lat: 24.8308031,
    lng: 67.0417865,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Faizan-e-Jilan (Block-8, Clifton)",
    area: "Clifton",
    lat: 24.8309946,
    lng: 67.0369682,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Faizan-e-Quran (near Vincy Mall, Block-9, Clifton)",
    area: "Clifton",
    lat: 24.829,
    lng: 67.034,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Saira Masjid (Kh-e-Jami, Punjab Colony, opp Football Ground)",
    area: "Clifton",
    lat: 24.833,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Al-Falah Masjid (P&T Colony)",
    area: "Clifton",
    lat: 24.834,
    lng: 67.039,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Faizan-e-Ghazali (New P&T Colony)",
    area: "Clifton",
    lat: 24.835,
    lng: 67.04,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Qamrul Islam Masjid (Punjab Colony)",
    area: "Clifton",
    lat: 24.836,
    lng: 67.041,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Bab-e-Rehmat Masjid (Gizri)",
    area: "Gizri",
    lat: 24.837,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Adam Masjid (Gizri)",
    area: "Gizri",
    lat: 24.838,
    lng: 67.043,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Mubarak Masjid Gizri",
    area: "Gizri",
    lat: 24.839,
    lng: 67.044,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Turab ul Haq (Anjuman Chowk, Upper Gizri)",
    area: "Gizri",
    lat: 24.84,
    lng: 67.045,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Nooria Razavia (Block-5 Clifton, Boat Basin)",
    area: "Clifton",
    lat: 24.8222662,
    lng: 67.0281143,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Al-Khair Masjid (Block-2 Clifton)",
    area: "Clifton",
    lat: 24.8154925,
    lng: 67.0190377,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Jamia Masjid Haider-e-Karar (Near Aga Khan Lab, Block-2 Clifton)",
    area: "Clifton",
    lat: 24.815,
    lng: 67.02,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Muhammadi (Shereen Jinnah Colony No.1 Clifton)",
    area: "Clifton",
    lat: 24.816,
    lng: 67.021,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Ghausia Barkatia Masjid (Near License Office, Neelum Colony)",
    area: "Clifton",
    lat: 24.817,
    lng: 67.022,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan-e-Attar (Neelum Colony)",
    area: "Clifton",
    lat: 24.818,
    lng: 67.023,
    parking: false,
    timings: { juma: "1:30" },
  },

  // ==================== SADDAR MOBILE MARKET ====================
  {
    name: "Jamia Masjid Al-Raheem (Kohe Noor Centre)",
    area: "Saddar",
    lat: 24.8508998,
    lng: 67.0001771,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Istar Siti Mall Masjid (5 Floor)",
    area: "Saddar",
    lat: 24.851,
    lng: 67.001,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Al Barkat Masjid (Nujaymi Mall)",
    area: "Saddar",
    lat: 24.852,
    lng: 67.002,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan KanzulAiman Masjid (Al Falah Market)",
    area: "Saddar",
    lat: 24.853,
    lng: 67.003,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jaye Namaz Shahjahan Market (5 Floor)",
    area: "Saddar",
    lat: 24.854,
    lng: 67.004,
    parking: false,
    timings: { juma: "" },
  },
  {
    name: "Faizan Meraj Masjid (Naz Plaza)",
    area: "Saddar",
    lat: 24.855,
    lng: 67.005,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Madni (Basho Centre)",
    area: "Saddar",
    lat: 24.856,
    lng: 67.006,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Faizan Shaaban Masjid (6 Floor Aman Tower)",
    area: "Saddar",
    lat: 24.857,
    lng: 67.007,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Jaye Namaz Paron Market",
    area: "Saddar",
    lat: 24.858,
    lng: 67.008,
    parking: false,
    timings: { juma: "" },
  },
  {
    name: "Jamia Masjid Aqsa (Akbar Road)",
    area: "Saddar",
    lat: 24.859,
    lng: 67.009,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jaye Namaz Leark Mall",
    area: "Saddar",
    lat: 24.86,
    lng: 67.01,
    parking: false,
    timings: { juma: "" },
  },
  {
    name: "Qasabaan Masjid (Korangi Bus Astaab)",
    area: "Saddar",
    lat: 24.861,
    lng: 67.011,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Bilal Masjid (Priedy Thana)",
    area: "Saddar",
    lat: 24.862,
    lng: 67.012,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Kachhi Memon Masjid (Saddar)",
    area: "Saddar",
    lat: 24.8589589,
    lng: 67.0295335,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Madina Masjid (Madina Centre Market)",
    area: "Saddar",
    lat: 24.864,
    lng: 67.014,
    parking: false,
    timings: { juma: "1:30" },
  },

  // ==================== GARDEN WEST / SHOW MARKET ====================
  {
    name: "Yumn Tayiba Shalimar Garden",
    area: "Garden West",
    lat: 24.8559187,
    lng: 67.0124839,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Faizan Zam Zam Masjid (Fawara Chowk)",
    area: "Garden West",
    lat: 24.856,
    lng: 67.013,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Faizan Milad Masjid (Garden Medical)",
    area: "Garden West",
    lat: 24.857,
    lng: 67.014,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Jamia Gilani Masjid",
    area: "Garden West",
    lat: 24.858,
    lng: 67.015,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Mohri Masjid (Fawara Chowk)",
    area: "Garden West",
    lat: 24.859,
    lng: 67.016,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Usman Ghani Masjid (Al-Akhani Ters)",
    area: "Garden West",
    lat: 24.86,
    lng: 67.017,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Ghouth Azam Masjid (Nida Apartments)",
    area: "Garden West",
    lat: 24.861,
    lng: 67.018,
    parking: false,
    timings: { juma: "***" },
  },
  {
    name: "Yaseen Masjid (Hussain Lashkri Veela)",
    area: "Garden West",
    lat: 24.862,
    lng: 67.019,
    parking: false,
    timings: { juma: "2:45" },
  },
  {
    name: "Firdaus Masjid (Pakistan Quarter)",
    area: "Garden West",
    lat: 24.863,
    lng: 67.02,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Madina Masjid (Madina Colony)",
    area: "Garden West",
    lat: 24.864,
    lng: 67.021,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Faizan Mustafa (Rahmat Kareem)",
    area: "Garden West",
    lat: 24.865,
    lng: 67.022,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Alana Masjid (Show Market)",
    area: "Garden West",
    lat: 24.866,
    lng: 67.023,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Baab ul Deen Masjid",
    area: "Garden West",
    lat: 24.867,
    lng: 67.024,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Bismillah Masjid (Show Market)",
    area: "Garden West",
    lat: 24.868,
    lng: 67.025,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Faizan Ajmeer Masjid (Show Market)",
    area: "Garden West",
    lat: 24.869,
    lng: 67.026,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Jamal Mustafa Masjid (Almari Gali)",
    area: "Garden West",
    lat: 24.87,
    lng: 67.027,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Kulli Jamia Masjid (Kachhi Masjid)",
    area: "Garden West",
    lat: 24.871,
    lng: 67.028,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Madina Masjid (Police Building)",
    area: "Garden West",
    lat: 24.872,
    lng: 67.029,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Madina Masjid (Police Headquarter)",
    area: "Garden West",
    lat: 24.873,
    lng: 67.03,
    parking: false,
    timings: { juma: "2:10" },
  },
  {
    name: "Faizan Siddiq Akbar (Stana Ters)",
    area: "Garden West",
    lat: 24.874,
    lng: 67.031,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Ramzan (Garden)",
    area: "Garden West",
    lat: 24.875,
    lng: 67.032,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Ghouthia (BI BI Factory)",
    area: "Garden West",
    lat: 24.876,
    lng: 67.033,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Faizan Shaaban (Shahzil Fawn Tower)",
    area: "Garden West",
    lat: 24.877,
    lng: 67.034,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Razia Sultana Masjid (Aagan Wali Gali)",
    area: "Garden West",
    lat: 24.878,
    lng: 67.035,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Faizan Milad Masjid (ANMIS Medical)",
    area: "Garden West",
    lat: 24.879,
    lng: 67.036,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Baanchia Hashim Khan",
    area: "Garden West",
    lat: 24.88,
    lng: 67.037,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jami Masjid Bilal Tower (Bilal Tower)",
    area: "Garden West",
    lat: 24.881,
    lng: 67.038,
    parking: false,
    timings: { juma: "3:30" },
  },
  {
    name: "Mujn Shah Bakhari Masjid (Garden Mgal)",
    area: "Garden West",
    lat: 24.882,
    lng: 67.039,
    parking: false,
    timings: { juma: "1:15" },
  },

  // ==================== USMAN ABAD / NIAZI COLONY ====================
  {
    name: "Faizan Manzil (Usman Abad)",
    area: "Usman Abad",
    lat: 24.8710144,
    lng: 67.016744,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Kachhi Jamia Masjid (Kaachhi Masjid)",
    area: "Usman Abad",
    lat: 24.872,
    lng: 67.017,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jamia Masjid Rahmania",
    area: "Usman Abad",
    lat: 24.873,
    lng: 67.018,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Jamia Masjid Faizan Qutb Madina",
    area: "Usman Abad",
    lat: 24.874,
    lng: 67.019,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Hashmi",
    area: "Usman Abad",
    lat: 24.875,
    lng: 67.02,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Jaye Namaz Aisha",
    area: "Usman Abad",
    lat: 24.876,
    lng: 67.021,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Islam Pora Masjid (Show Market)",
    area: "Usman Abad",
    lat: 24.877,
    lng: 67.022,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Azeem Plaza (Show Market)",
    area: "Usman Abad",
    lat: 24.878,
    lng: 67.023,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Kachhor Wali Mohri Jamia Masjid",
    area: "Usman Abad",
    lat: 24.879,
    lng: 67.024,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Jamia Masjid Bilal Niazi Colony",
    area: "Niazi Colony",
    lat: 24.88,
    lng: 67.025,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Noorani Sabri Masjid",
    area: "Niazi Colony",
    lat: 24.881,
    lng: 67.026,
    parking: false,
    timings: { juma: "1:55" },
  },

  // ==================== SOLDIER BAZAR / GARDEN EAST ====================
  {
    name: "Jamia Masjid KanzulAiman",
    area: "Soldier Bazar",
    lat: 24.8580083,
    lng: 67.0224722,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Ismail Masjid (Nalay Wali Gali)",
    area: "Soldier Bazar",
    lat: 24.859,
    lng: 67.023,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Qasim Masjid (Noor College Wali Gali)",
    area: "Soldier Bazar",
    lat: 24.86,
    lng: 67.024,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Attar Masjid (Nzdek Fatimia Hospital)",
    area: "Soldier Bazar",
    lat: 24.861,
    lng: 67.025,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Ameer Muawiya Masjid (Taj Petrol Pump Wali Gali)",
    area: "Soldier Bazar",
    lat: 24.862,
    lng: 67.026,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Siddiq Akbar Razi Allah Anhu (Jahangir Road)",
    area: "Soldier Bazar",
    lat: 24.863,
    lng: 67.027,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Faizan Sunnat Masjid (Garden East)",
    area: "Garden East",
    lat: 24.864,
    lng: 67.028,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Bahaar KanzulAiman Masjid (Garden East)",
    area: "Garden East",
    lat: 24.865,
    lng: 67.029,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Faizan Siddiq Akbar Razi Allah Anhu Masjid (Garden East)",
    area: "Garden East",
    lat: 24.866,
    lng: 67.03,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Ghouth ul Azam Masjid (Crown Apartments, Maryam Diwan Wali Gali)",
    area: "Garden East",
    lat: 24.867,
    lng: 67.031,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Madina Masjid (Nzdek Chandni Chowk, Nishtar Road)",
    area: "Soldier Bazar",
    lat: 24.868,
    lng: 67.032,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Masoom Shah Masjid (Chandni Chowk Hameed Colony)",
    area: "Soldier Bazar",
    lat: 24.869,
    lng: 67.033,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Gulzar Habeeb Masjid",
    area: "Garden East",
    lat: 24.87,
    lng: 67.034,
    parking: false,
    timings: { juma: "3:00" },
  },
  {
    name: "Khadija-tul-Kubra Masjid (Dholi Kahata)",
    area: "Garden East",
    lat: 24.871,
    lng: 67.035,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Noor Habeeb Masjid (Sipari Compound, Al Furqan Academy)",
    area: "Garden East",
    lat: 24.872,
    lng: 67.036,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Jamia Masjid Al-Harmain Lakhaani Apartment (Punjab Town)",
    area: "Garden East",
    lat: 24.873,
    lng: 67.037,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Zulaikha Masjid (Parsi Colony)",
    area: "Garden East",
    lat: 24.874,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Masjid Yousuf Soldier Bazar No. 1 Kachi Para Colony",
    area: "Soldier Bazar",
    lat: 24.875,
    lng: 67.039,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Khizan ul Irfan Masjid (Nzdek Nishtar Park)",
    area: "Garden East",
    lat: 24.876,
    lng: 67.04,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Mustafi Garden (Nzdek Fatimid Blood Bank)",
    area: "Garden East",
    lat: 24.877,
    lng: 67.041,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Allah Wali Masjid (Soldier Bazar ke Baraber)",
    area: "Soldier Bazar",
    lat: 24.878,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Qadri Masjid",
    area: "Garden East",
    lat: 24.879,
    lng: 67.043,
    parking: false,
    timings: { juma: "3:35" },
  },
  {
    name: "Jamia Masjid Siddiqia (Soldier Bazar 2)",
    area: "Soldier Bazar",
    lat: 24.88,
    lng: 67.044,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Jamia Masjid Ghousia (Baraangoth Losabila)",
    area: "Garden East",
    lat: 24.881,
    lng: 67.045,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Billy Wio Masjid (Garden East)",
    area: "Garden East",
    lat: 24.882,
    lng: 67.046,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jaye Namaz Shahzada Sweet Thao Mehran Girl Hotel Wali Gali",
    area: "Garden East",
    lat: 24.883,
    lng: 67.047,
    parking: false,
    timings: { juma: "" },
  },
  {
    name: "Jame ul Madina Jamia Masjid Faizan KanzulAiman Nzdek Kebabs",
    area: "Garden East",
    lat: 24.884,
    lng: 67.048,
    parking: false,
    timings: { juma: "" },
  },

  // ==================== JODIA BAZAR ====================
  {
    name: "Jamia Masjid Noorani (New Chali)",
    area: "Jodia Bazar",
    lat: 24.858,
    lng: 66.993,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jaye Namaz Faizan Fatima (Puna Wala Pehli Manzil)",
    area: "Jodia Bazar",
    lat: 24.859,
    lng: 66.994,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Saabwani Masjid (Jozya Bazar)",
    area: "Jodia Bazar",
    lat: 24.86,
    lng: 66.995,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Meen Masjid (Muslih ul Deen Garden)",
    area: "Jodia Bazar",
    lat: 24.861,
    lng: 66.996,
    parking: false,
    timings: { juma: "1:45" },
  },

  // ==================== MITHADAR ====================
  {
    name: "Adam Masjid (Jozya Bazar)",
    area: "Mithadar",
    lat: 24.862,
    lng: 66.997,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Mubarak Masjid (Idhi Centre)",
    area: "Mithadar",
    lat: 24.863,
    lng: 66.998,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Mohri Masjid (Kaghzi Bazar, Wadla Baal)",
    area: "Mithadar",
    lat: 24.864,
    lng: 66.999,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Subs Masjid (Sarrafa Bazar)",
    area: "Mithadar",
    lat: 24.865,
    lng: 67.0,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Umme Attar Masjid (Gunoo Gali)",
    area: "Mithadar",
    lat: 24.866,
    lng: 67.001,
    parking: false,
    timings: { juma: "3:20" },
  },

  // ==================== KAGZI BAZAR ====================
  {
    name: "Noor Masjid (Kaghzi Bazar)",
    area: "Kagzi Bazar",
    lat: 24.867,
    lng: 67.002,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Qazi Masjid (Do Pane Wali Gali)",
    area: "Kagzi Bazar",
    lat: 24.868,
    lng: 67.003,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Mustafi Masjid (Kaghzi Bazar)",
    area: "Kagzi Bazar",
    lat: 24.869,
    lng: 67.004,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Madina Masjid (Astana Qasim Babo ke Saamne)",
    area: "Kagzi Bazar",
    lat: 24.87,
    lng: 67.005,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Gantri Masjid (Peer Chishti Shah Baba Mazar)",
    area: "Kagzi Bazar",
    lat: 24.871,
    lng: 67.006,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Badami Masjid (Bantwa Hospital Wali Gali)",
    area: "Kagzi Bazar",
    lat: 24.872,
    lng: 67.007,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Kachori Masjid (Peer Syed Bheura Badshah)",
    area: "Kagzi Bazar",
    lat: 24.873,
    lng: 67.008,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Alif Masjid",
    area: "Kagzi Bazar",
    lat: 24.874,
    lng: 67.009,
    parking: false,
    timings: { juma: "2:35" },
  },
  {
    name: "Nabida Masjid (Abel Chowk)",
    area: "Kagzi Bazar",
    lat: 24.875,
    lng: 67.01,
    parking: false,
    timings: { juma: "1:00" },
  },

  // ==================== KHARADAR ====================
  {
    name: "Bismillah Masjid",
    area: "Kharadar",
    lat: 24.857,
    lng: 66.99,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Memon Masjid (Bolton Market)",
    area: "Kharadar",
    lat: 24.858,
    lng: 66.991,
    parking: false,
    timings: { juma: "1:25" },
  },
  {
    name: "Bukhari Masjid (Police Chowki)",
    area: "Kharadar",
    lat: 24.859,
    lng: 66.992,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Madina Masjid (Punjabi Club)",
    area: "Kharadar",
    lat: 24.86,
    lng: 66.993,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Akhound Masjid (Chahagala Street)",
    area: "Kharadar",
    lat: 24.861,
    lng: 66.994,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Okhayi Masjid (Gilani Centre Wali Gali)",
    area: "Kharadar",
    lat: 24.862,
    lng: 66.995,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Shaheed Masjid",
    area: "Kharadar",
    lat: 24.863,
    lng: 66.996,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Hyderi Masjid (Sabzwari Mazar Shareef)",
    area: "Kharadar",
    lat: 24.864,
    lng: 66.997,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Qadri Masjid (Nzdek Okhayi Memon School)",
    area: "Kharadar",
    lat: 24.865,
    lng: 66.998,
    parking: false,
    timings: { juma: "3:40" },
  },
  {
    name: "Katiana Memon Hospital (1st Floor)",
    area: "Kharadar",
    lat: 24.866,
    lng: 66.999,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Plastic Market (1st Floor)",
    area: "Kharadar",
    lat: 24.867,
    lng: 67.0,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Pakistan Stock Exchange (1st Floor)",
    area: "Kharadar",
    lat: 24.868,
    lng: 67.001,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Ghotia Masjid (Custom Trade Tower Building, 2nd Floor)",
    area: "Kharadar",
    lat: 24.869,
    lng: 67.002,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Hajiani Ziton (Machhi Miyani Market near Jamal Shah Baba Mazar)",
    area: "Kharadar",
    lat: 24.87,
    lng: 67.003,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Muslahi Muslih ud Deen (Shameh Plaza Kharadar Block C.3)",
    area: "Kharadar",
    lat: 24.871,
    lng: 67.004,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Falak Naz Tower (6 Floor Roby Centre)",
    area: "Kharadar",
    lat: 24.872,
    lng: 67.005,
    parking: false,
    timings: { juma: "1:15" },
  },

  // ==================== BAKRA PIRI / KALAKOT / LYARI ====================
  {
    name: "Madni Masjid (Mirza Adam Khan Road, Dhowi Ghat)",
    area: "Bakra Piri",
    lat: 24.848,
    lng: 66.982,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Aalishan Masjid (Mirza Adam Khan Road Boatil ke Saamne)",
    area: "Bakra Piri",
    lat: 24.849,
    lng: 66.983,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Ganj Shakar Masjid (Mirza Adam Khan Road Bakrapiri Pul ke Paas)",
    area: "Bakra Piri",
    lat: 24.85,
    lng: 66.984,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Madina Masjid (Mirza Meewa Shah Road Bakra Piri)",
    area: "Bakra Piri",
    lat: 24.851,
    lng: 66.985,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Riyani Masjid (Miran Naka Nzdek Duda Velaich)",
    area: "Lyari",
    lat: 24.852,
    lng: 66.986,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Noor Syed na Ghous Pak Jaye Namaz (Mondra Muhalla Bakrapiri)",
    area: "Bakra Piri",
    lat: 24.853,
    lng: 66.987,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Mahboob Masjid (Darul Uloom Faizan Nabawi Bakrapiri)",
    area: "Bakra Piri",
    lat: 24.854,
    lng: 66.988,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Muhammadi Masjid (Kalakot Police Station Liayri)",
    area: "Kalakot",
    lat: 24.855,
    lng: 66.989,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Mahboob Masjid (Muttasil Idara Faizan ul Quran Khadhbasti)",
    area: "Lyari",
    lat: 24.856,
    lng: 66.99,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Ghazi Masjid (Haji Abbas Khan Road)",
    area: "Lyari",
    lat: 24.857,
    lng: 66.991,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Subhani Masjid (Bakrapiri)",
    area: "Bakra Piri",
    lat: 24.858,
    lng: 66.992,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Siddiq Akbar Masjid (Basham Lassi Asrait Sangolin)",
    area: "Lyari",
    lat: 24.859,
    lng: 66.993,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Riyani Masjid (Sangolin Gali B-9)",
    area: "Lyari",
    lat: 24.86,
    lng: 66.994,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Buri Masjid (New Kambar Waaza)",
    area: "Lyari",
    lat: 24.861,
    lng: 66.995,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Faizan Auliya Masjid (Abu Manzil Gali Kambharwaaza)",
    area: "Lyari",
    lat: 24.862,
    lng: 66.996,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Sabir Shah Masjid (New Kambar Waaza)",
    area: "Lyari",
    lat: 24.863,
    lng: 66.997,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Rizwan Masjid (Tovaleen Gali No. 11)",
    area: "Lyari",
    lat: 24.864,
    lng: 66.998,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Anwar Muhammadi Masjid (Tovaleen Gali No. 16)",
    area: "Lyari",
    lat: 24.865,
    lng: 66.999,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Hanfia Masjid (Chaakiwaza Lyari)",
    area: "Lyari",
    lat: 24.866,
    lng: 67.0,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Momin Masjid (Momin Mola Madd Chaakiwaza Lyari)",
    area: "Lyari",
    lat: 24.867,
    lng: 67.001,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Noor Masjid (Ghareeb Shah)",
    area: "Lyari",
    lat: 24.868,
    lng: 67.002,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Hira Masjid (Caroleen Gali No. 9)",
    area: "Lyari",
    lat: 24.869,
    lng: 67.003,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Farooki Masjid (Adam Chani Sangolin)",
    area: "Lyari",
    lat: 24.87,
    lng: 67.004,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Foutolin Masjid",
    area: "Lyari",
    lat: 24.871,
    lng: 67.005,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Haji Pincher Masjid (Kalakot)",
    area: "Kalakot",
    lat: 24.872,
    lng: 67.006,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Ghulaman Muhammad Sheebrook Kalakot",
    area: "Kalakot",
    lat: 24.873,
    lng: 67.007,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Nabi Dad Masjid (Brrohi Chowk)",
    area: "Lyari",
    lat: 24.874,
    lng: 67.008,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Jamia Masjid Waajed Shah (Miyanouli Colony Dhowi Ghat)",
    area: "Bakra Piri",
    lat: 24.875,
    lng: 67.009,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faiz Gilani Masjid (Mirza Dada Mian Qabarstan)",
    area: "Bakra Piri",
    lat: 24.876,
    lng: 67.01,
    parking: false,
    timings: { juma: "3:00" },
  },

  // ==================== AGRA TAJ / BAHAR COLONY ====================
  {
    name: "Noorani Masjid (Agra Taj)",
    area: "Agra Taj",
    lat: 24.877,
    lng: 67.011,
    parking: false,
    timings: { juma: "1:50" },
  },
  {
    name: "Madni Masjid (Taj Masjid Road)",
    area: "Agra Taj",
    lat: 24.878,
    lng: 67.012,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Faizan Raza Masjid (Taj Masjid Road Agra Taj Liyari)",
    area: "Agra Taj",
    lat: 24.879,
    lng: 67.013,
    parking: false,
    timings: { juma: "2:45" },
  },
  {
    name: "Faizan Ghous Al-Azam Gilani Masjid (Hanfia Masjid Road)",
    area: "Agra Taj",
    lat: 24.88,
    lng: 67.014,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Hanfia Masjid (Agra Taj)",
    area: "Agra Taj",
    lat: 24.881,
    lng: 67.015,
    parking: false,
    timings: { juma: "2:25" },
  },
  {
    name: "Dua Masjid (Ghotia Road Agra Taj Colony)",
    area: "Agra Taj",
    lat: 24.882,
    lng: 67.016,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Gulzar Habeeb Masjid (Ghotia Road)",
    area: "Agra Taj",
    lat: 24.883,
    lng: 67.017,
    parking: false,
    timings: { juma: "1:20" },
  },
  {
    name: "Ghotia Masjid (Ghotia Road, Agra Taj)",
    area: "Agra Taj",
    lat: 24.884,
    lng: 67.018,
    parking: false,
    timings: { juma: "1:10" },
  },
  {
    name: "Rahmania Masjid (Juma Belooch Road Gali A/16 Liayri)",
    area: "Lyari",
    lat: 24.885,
    lng: 67.019,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Khizra Masjid (New Kulri Bungore Abad Gali A/13 No. A/13 Yoosi)",
    area: "Lyari",
    lat: 24.886,
    lng: 67.02,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Ibrahimi Masjid (Mandara Muhalla, Shah Abdul Latif Bhattai Road)",
    area: "Lyari",
    lat: 24.887,
    lng: 67.021,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Siddiq Akbar Masjid (Ahmad Shah Bukhari Road)",
    area: "Agra Taj",
    lat: 24.888,
    lng: 67.022,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Noor ul Irfan Masjid (Al Falah Road Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.889,
    lng: 67.023,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Fatima Masjid (Gali 2# G Road Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.89,
    lng: 67.024,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Noor Mustafi Masjid (C Road Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.891,
    lng: 67.025,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Ameer Hamza Masjid (A Road Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.892,
    lng: 67.026,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Ghazi Baba Masjid (Mirza Adam Khan Road Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.893,
    lng: 67.027,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Gulzar Madina Masjid (Market Road Gali 14 Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.894,
    lng: 67.028,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Noor Mustafi Masjid (Liayri Station Miran Naka)",
    area: "Lyari",
    lat: 24.895,
    lng: 67.029,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Al-Madina Masjid (Peer Manzal Shah Road Aabid Abad)",
    area: "Lyari",
    lat: 24.896,
    lng: 67.03,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Noor Ali Noor Masjid (Gulistan Colony Liayri)",
    area: "Lyari",
    lat: 24.897,
    lng: 67.031,
    parking: false,
    timings: { juma: "1:55" },
  },
  {
    name: "Bazara Masjid (Nzdek Liayri General Hospital)",
    area: "Lyari",
    lat: 24.898,
    lng: 67.032,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Khadija-tul-Kubra Masjid (Mola Madd Astaab, Miran Naka)",
    area: "Lyari",
    lat: 24.899,
    lng: 67.033,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Zakria Masjid (Miran Naka Lassi Muhalla)",
    area: "Lyari",
    lat: 24.9,
    lng: 67.034,
    parking: false,
    timings: { juma: "1:25" },
  },
  {
    name: "Hajiani Rabia Basri Masjid (Gali 20, Bahar Colony)",
    area: "Bahar Colony",
    lat: 24.901,
    lng: 67.035,
    parking: false,
    timings: { juma: "1:35" },
  },

  // ==================== MOOSI LINE / NAYA ABAD ====================
  {
    name: "Muhammadi Masjid (Nzdek Sounara Baal Moosi Line)",
    area: "Moosi Line",
    lat: 24.902,
    lng: 67.036,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Kausar Masjid (Moosi Line)",
    area: "Moosi Line",
    lat: 24.903,
    lng: 67.037,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Attar Masjid (Samia Masjid Moosi Line)",
    area: "Moosi Line",
    lat: 24.904,
    lng: 67.038,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Madina Masjid (Memon Sosanati Khuda Masjid)",
    area: "Moosi Line",
    lat: 24.905,
    lng: 67.039,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Halima Ishaq Masjid (Khuda Market Nzdek Malbaari Hotel)",
    area: "Moosi Line",
    lat: 24.906,
    lng: 67.04,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Faizan Auliya Masjid (Niyaabad)",
    area: "Naya Abad",
    lat: 24.907,
    lng: 67.041,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Jamia Masjid Faizan Abu Attar (Moosi Line Musafir Khana Gali)",
    area: "Moosi Line",
    lat: 24.908,
    lng: 67.042,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Maryam Masjid (Niyaabad)",
    area: "Naya Abad",
    lat: 24.909,
    lng: 67.043,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Haji Mala Masjid (Niyaabad Gali No. 7)",
    area: "Naya Abad",
    lat: 24.91,
    lng: 67.044,
    parking: false,
    timings: { juma: "2:30" },
  },
  {
    name: "Kanzuliman Masjid (Gali No. 4 Darya Abad)",
    area: "Naya Abad",
    lat: 24.911,
    lng: 67.045,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Noor Habeeb Masjid (Mama Hotel Niyaabad)",
    area: "Naya Abad",
    lat: 24.912,
    lng: 67.046,
    parking: false,
    timings: { juma: "1:00" },
  },
  {
    name: "Noorani Masjid (Niyazi Chowk Niya Abad)",
    area: "Naya Abad",
    lat: 24.913,
    lng: 67.047,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Firdous Masjid (Mazri Por Truck Astaineh)",
    area: "Naya Abad",
    lat: 24.914,
    lng: 67.048,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Faizan Ishq Rasool Masjid (Nzdek Benazeer Bakery Niya Abad)",
    area: "Naya Abad",
    lat: 24.915,
    lng: 67.049,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Darul Islam Masjid (Shamsul Deen Muhammad Colony)",
    area: "Naya Abad",
    lat: 24.916,
    lng: 67.05,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Karman Wali Masjid (Wazeer Minshan Relnoway Colony ICI)",
    area: "Naya Abad",
    lat: 24.917,
    lng: 67.051,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Baghdadi Masjid (Baghdadi Thana)",
    area: "Naya Abad",
    lat: 24.918,
    lng: 67.052,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Qadri Masjid (Yousuf Baroon Road Gali 5 Baghdadi)",
    area: "Naya Abad",
    lat: 24.919,
    lng: 67.053,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Faizan Ameer Muawiya Masjid (Fada Hussain Sheikha Road)",
    area: "Naya Abad",
    lat: 24.92,
    lng: 67.054,
    parking: false,
    timings: { juma: "2:15" },
  },
  {
    name: "Baronia Masjid (Shah Baig Line Liayri 1)",
    area: "Lyari",
    lat: 24.921,
    lng: 67.055,
    parking: false,
    timings: { juma: "2:00" },
  },
  {
    name: "Siyana Masjid Noor Muhammadi (Haji Peer Muhammad Road Liayri)",
    area: "Lyari",
    lat: 24.922,
    lng: 67.056,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Mulla Umar Masjid (Athe Chowk Li Market)",
    area: "Lyari",
    lat: 24.923,
    lng: 67.057,
    parking: false,
    timings: { juma: "1:35" },
  },
  {
    name: "Turk Masjid (Li Market)",
    area: "Lyari",
    lat: 24.924,
    lng: 67.058,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Madrasa wa Jamia Masjid Faiz Attar (Li Market)",
    area: "Lyari",
    lat: 24.925,
    lng: 67.059,
    parking: false,
    timings: { juma: "1:05" },
  },
  {
    name: "Farooki Masjid (Kambila Astaab Gali 1 Rouncha Muhalla)",
    area: "Lyari",
    lat: 24.926,
    lng: 67.06,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Halima Masjid (Mewa Shah Qabarstan)",
    area: "Lyari",
    lat: 24.927,
    lng: 67.061,
    parking: false,
    timings: { juma: "1:15" },
  },
  {
    name: "Dilkasha Masjid (Mewa Shah Qabarstan)",
    area: "Lyari",
    lat: 24.928,
    lng: 67.062,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Mewa Shah Dargah Wali",
    area: "Lyari",
    lat: 24.929,
    lng: 67.063,
    parking: false,
    timings: { juma: "1:45" },
  },
  {
    name: "Khadija-tul-Kubra Masjid (Abid Abad)",
    area: "Naya Abad",
    lat: 24.93,
    lng: 67.064,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Jamia Masjid Ghousia (Gali 10 Darya Abad)",
    area: "Naya Abad",
    lat: 24.931,
    lng: 67.065,
    parking: false,
    timings: { juma: "1:30" },
  },
  {
    name: "Bilal Masjid (Gali 6 Badshah Khan Road Darya Abad)",
    area: "Naya Abad",
    lat: 24.932,
    lng: 67.066,
    parking: false,
    timings: { juma: "1:40" },
  },
  {
    name: "Masjid Umme Sakina (Gali 3 Muhammadi Muhalla Madina Gali)",
    area: "Naya Abad",
    lat: 24.933,
    lng: 67.067,
    parking: false,
    timings: { juma: "1:30" },
  },
];

async function seed() {
  // Import your connectDB and Masjid model here
  await connectDB();
  await Masjid.deleteMany({});
  await Masjid.insertMany(MASJID_DB_PDF);
  console.log(`🕌 ${MASJID_DB_PDF.length} Masjidein ready hain seed karne ke liye!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Error:", err);
  process.exit(1);
});